# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["production"]
  # pull_request:
  #   branches: ["production"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      # - name: Goto client
      #   run: cd client

      - name: Configure NPM
        working-directory: client
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          echo "always-auth: true" >> .npmrc

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: client/package-lock.json
      - name: build client
        working-directory: client
        run: |
          npm ci
          npm run build
          cp -a ./dist/. /var/www/html

      # - name: Goto cerver
      #   run: cd ../server

      - name: Configure NPM
        working-directory: server
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          echo "always-auth: true" >> .npmrc

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: server/package-lock.json
      - name: build server
        working-directory: server
        run: |
          npm ci
          npm run start
